### ISSUE TITLE
Недостаточные условия проверки дубликата элемента

### ISSUE THREAD

**Issue by vtsurka** [notamedia/bitrix-i18n#1]
В class ElementHandler метод checkDoubleElement ищет дубликат только по следующим параметрам:

```
                    'IBLOCK_ID' => $fields['IBLOCK_ID'],
                    'PROPERTY_' . $settings['PROP_CODE_PUBLIC_ID'] => $publicId,
                    'PROPERTY_' . $settings['PROP_CODE_LANG'] => $langId,
                    '!ID' => $fields['ID'],
```

Собственно у нас будет выбрасывать ошибку каждый раз, если элементов больше одного.

Думаю необходимо добавить условие по CODE

**Comment by niksamokhvalov** [comment]
По-моему тут всё верно: два элемента с одним и тем же публичным идентификатором и языком в системе быть не должно, это противоречит правилам интернационализации. Здесь как раз ищется элемент с таким же публичным ID и языком, но с другим идентификатором. Если найдём, это означает, что редактор пытается создать элемент-дубль.

**Comment by vtsurka** [comment]
У вас просто это отрабатывает и на update функции, прошу прощения, что сразу не отписал, что имею ввиду ее.

Case:
Новость А { LANG:ru , ID: 444, PUBLIC_ID:444}
Новость Б { LANG:ua, ID:445, PUBLIC_ID:444}

в итоге при обновлении новости будет происходить ошибка, т.к. языковая версия новости существует уже

**Comment by niksamokhvalov** [comment]
К сожалению, я не могу воспроизвести эту ошибку. Новости создаются в разных языковых версиях с одним публичным номером, и корректно обновляются. Вы можете написать используемую версию модуля и последовательность действий для воспроизведения ошибки?
